apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb-local
  namespace: makanlah
spec:
  replicas: 1
  selector:
    matchLabels: { app: dynamodb-local }
  template:
    metadata:
      labels: { app: dynamodb-local }
    spec:
      containers:
        - name: dynamodb-local
          image: amazon/dynamodb-local:latest
          args: ["-jar", "DynamoDBLocal.jar", "-inMemory", "-sharedDb"]
          ports:
            - containerPort: 8000
          resources:
            requests: { cpu: 100m, memory: 256Mi }
            limits: { cpu: 500m, memory: 512Mi }
---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb-local
  namespace: makanlah
spec:
  selector: { app: dynamodb-local }
  ports:
    - port: 8000
      targetPort: 8000
